MenuItem.create!([
  {name: "The Big Salad", description: "a big salad", category: "Salads", restaurant_id: 1, archived: false, price: 7.0},
  {name: "Small Salad", description: "a normal sized salad", category: "Salads", restaurant_id: 1, archived: false, price: 1.5},
  {name: "Coffee", description: "black, with no cream", category: "Beverages", restaurant_id: 1, archived: false, price: 1.5},
  {name: "Iced Tea", description: "Sweet or not", category: "Beverages", restaurant_id: 1, archived: false, price: 2.0},
  {name: "Chicken Salad", description: "Best on Rye", category: "Sandwiches", restaurant_id: 1, archived: false, price: 6.5}
])

Restaurant.create!([
  {name: "Monk's Cafe", cuisine: "American", address: "2880 Broadway", city: "New York City", state: "NY", yelp_id: nil, opens_at: 800, closes_at: 2200, delivery_min: 12.0, delivery_fee: 2.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/1.jpg"},
  {name: "Hop Shing", cuisine: "Chinese", address: "9 Chatham Square", city: "New York City", state: "NY", yelp_id: nil, opens_at: 800, closes_at: 2200, delivery_min: 8.0, delivery_fee: 1.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/2.jpg"},
  {name: "Soup Stand", cuisine: "Soups", address: "259-A West 55th Street", city: "New York City", state: "NY", yelp_id: nil, opens_at: 1100, closes_at: 1800, delivery_min: 0.0, delivery_fee: 0.0, takeout_only: true, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/3.jpg"},
  {name: "Dream Cafe", cuisine: "Pakistani", address: "478 9th Ave", city: "New York City", state: "NY", yelp_id: nil, opens_at: 1000, closes_at: 2200, delivery_min: 4.75, delivery_fee: 3.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/4.jpg"},
  {name: "Pomodoro Roso", cuisine: "Italian", address: "229 Columbus Ave", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1300, closes_at: 2300, delivery_min: 0.0, delivery_fee: 0.0, takeout_only: true, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/5.jpg"},
  {name: "Paisano", cuisine: "Italian", address: "2287 1st Ave\t1100", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1100, closes_at: 2200, delivery_min: 0.0, delivery_fee: 0.0, takeout_only: true, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/6.jpg"},
  {name: "Royale Pastry Shop", cuisine: "Bakery", address: "237 West 72nd St", city: "New York City", state: "New York", yelp_id: nil, opens_at: 800, closes_at: 2200, delivery_min: 12.0, delivery_fee: 3.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/7.jpg"},
  {name: "Hunan 5th Avenue", cuisine: "Chinese", address: "323 5th Ave", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1100, closes_at: 2200, delivery_min: 0.0, delivery_fee: 0.0, takeout_only: true, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/8.jpg"},
  {name: "Papaya King", cuisine: "Hot Dogs", address: "2090 Broadway", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1130, closes_at: 2100, delivery_min: 10.0, delivery_fee: 3.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/9.jpg"},
  {name: "Mendy's", cuisine: "Deli", address: "61 E. 64th Street", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1030, closes_at: 2200, delivery_min: 12.0, delivery_fee: 2.5, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/10.jpg"},
  {name: "Kenny Roger's Roasters", cuisine: "American", address: "2055 Broadway", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1000, closes_at: 2200, delivery_min: 15.0, delivery_fee: 2.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/11.jpg"},
  {name: "Beach Café", cuisine: "American", address: "1326 Second Ave", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1200, closes_at: 2300, delivery_min: 12.0, delivery_fee: 2.5, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/12.jpg"},
  {name: "Pete's Tavern", cuisine: "American", address: "129 E. 18th St", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1100, closes_at: 2300, delivery_min: 0.0, delivery_fee: 0.0, takeout_only: true, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/13.jpg"},
  {name: "H & H Bagles", cuisine: "Bakery", address: "2239 Broadway", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1100, closes_at: 2300, delivery_min: 8.0, delivery_fee: 1.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/14.jpg"},
  {name: "Reggie's Diner", cuisine: "American", address: "682 11th Ave", city: "New York City", state: "New York", yelp_id: nil, opens_at: 800, closes_at: 2300, delivery_min: 12.0, delivery_fee: 4.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/15.jpg"},
  {name: "Fitzpatrick's Bar and Grill", cuisine: "American", address: "1641 Second Ave", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1200, closes_at: 2300, delivery_min: 0.0, delivery_fee: 0.0, takeout_only: true, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/16.jpg"}
])
