MenuItem.create!([
  {name: "The Big Salad", description: "A big salad", category: "Salads", restaurant_id: 1, archived: false, price: 7.0},
  {name: "Small Salad", description: "A normal sized salad", category: "Salads", restaurant_id: 1, archived: false, price: 1.5},
  {name: "Coffee", description: "Black, with no cream", category: "Beverages", restaurant_id: 1, archived: false, price: 1.5},
  {name: "Iced Tea", description: "Sweet or not", category: "Beverages", restaurant_id: 1, archived: false, price: 2.0},
  {name: "Chicken Salad", description: "Best on Rye", category: "Sandwiches", restaurant_id: 1, archived: false, price: 6.5},
  {name: "\tChef Salad\t", description: "\tWith a hard-boild egg, ranch dressing\t", category: "\tSalads\t", restaurant_id: 1, archived: false, price: 5.5},
  {name: "\tGreek Salad\t", description: "\tWith check, feta cheese, and olives\t", category: "\tSalads\t", restaurant_id: 1, archived: false, price: 6.5},
  {name: "\tChicken Sandwich\t", description: "\tOn a burger bun with lettuce and tomato\t", category: "\tSandwiches\t", restaurant_id: 1, archived: false, price: 6.0},
  {name: "\tThe Reuben\t", description: "\tOn rye bread, with sauerkraut\t", category: "\tSandwiches\t", restaurant_id: 1, archived: false, price: 7.5},
  {name: "\tBLT\t", description: "\tBacon, lettuce, and tomato with fries\t", category: "\tSandwiches\t", restaurant_id: 1, archived: false, price: 5.5},
  {name: "\tHambuger\t", description: "\tQuarter or triple pounder with American cheese with fries\t", category: "\tSandwiches\t", restaurant_id: 1, archived: false, price: 6.5},
  {name: "\tBacon and Eggs\t", description: "\t2 eggs (any style) with two slices of bacon, and bread\t", category: "\tBreakfast\t", restaurant_id: 1, archived: false, price: 8.0},
  {name: "\tOmelette\t", description: "\t3 eggs, with any combination of toppings\t", category: "\tBreakfast\t", restaurant_id: 1, archived: false, price: 7.0},
  {name: "\tPancakes\t", description: "\t3 pancakes, with butter and maple syrup\t", category: "\tBreakfast\t", restaurant_id: 1, archived: false, price: 7.0},
  {name: "\tFlapjacks\t", description: "\tLike pancakes, but smaller\t", category: "\tBreakfast\t", restaurant_id: 1, archived: false, price: 6.0},
  {name: "\tSoda\t", description: "\tCoke products\t", category: "\tBeverages\t", restaurant_id: 1, archived: false, price: 2.0},
  {name: "\tJuice\t", description: "\tOrange or apple\t", category: "\tBeverages\t", restaurant_id: 1, archived: false, price: 2.0},
  {name: "\tMilk\t", description: "\tWhite or chocolate\t", category: "\tBeverages\t", restaurant_id: 1, archived: false, price: 3.0},
  {name: "\tMilkshake\t", description: "\tChocolate, vanilla, or mixed\t", category: "\tBeverages\t", restaurant_id: 1, archived: false, price: 4.0},
  {name: "\tNormal-sized salad\t", description: "\tJust a normal salad\t", category: "\tSalads\t", restaurant_id: 15, archived: false, price: 5.0},
  {name: "\tChef Salad\t", description: "\tWith a hard-boild egg, ranch dressing\t", category: "\tSalads\t", restaurant_id: 15, archived: false, price: 5.5},
  {name: "\tGreek Salad\t", description: "\tWith check, feta cheese, and olives\t", category: "\tSalads\t", restaurant_id: 15, archived: false, price: 6.5},
  {name: "\tChicken Sandwich\t", description: "\tOn a burger bun with lettuce and tomato\t", category: "\tSandwiches\t", restaurant_id: 15, archived: false, price: 6.0},
  {name: "\tThe Reuben\t", description: "\tOn rye bread, with sauerkraut\t", category: "\tSandwiches\t", restaurant_id: 15, archived: false, price: 7.5},
  {name: "\tBLT\t", description: "\tBacon, lettuce, and tomato with fries\t", category: "\tSandwiches\t", restaurant_id: 15, archived: false, price: 5.5},
  {name: "\tHambuger\t", description: "\tQuarter or triple pounder with American cheese with fries\t", category: "\tSandwiches\t", restaurant_id: 15, archived: false, price: 6.5},
  {name: "\tBacon and Eggs\t", description: "\t2 eggs (any style) with two slices of bacon, and bread\t", category: "\tBreakfast\t", restaurant_id: 15, archived: false, price: 8.0},
  {name: "\tOmelette\t", description: "\t3 eggs, with any combination of toppings\t", category: "\tBreakfast\t", restaurant_id: 15, archived: false, price: 7.0},
  {name: "\tPancakes\t", description: "\t3 pancakes, with butter and maple syrup\t", category: "\tBreakfast\t", restaurant_id: 15, archived: false, price: 7.0},
  {name: "\tFlapjacks\t", description: "\tLike pancakes, but smaller\t", category: "\tBreakfast\t", restaurant_id: 15, archived: false, price: 6.0},
  {name: "\tSoda\t", description: "\tCoke products\t", category: "\tBeverages\t", restaurant_id: 15, archived: false, price: 2.0},
  {name: "\tJuice\t", description: "\tOrange or apple\t", category: "\tBeverages\t", restaurant_id: 15, archived: false, price: 2.0},
  {name: "\tMilk\t", description: "\tWhite or chocolate\t", category: "\tBeverages\t", restaurant_id: 15, archived: false, price: 3.0},
  {name: "\tMilkshake\t", description: "\tChocolate, vanilla, or mixed\t", category: "\tBeverages\t", restaurant_id: 15, archived: false, price: 4.0},
  {name: "\tGeneral Tso Chicken\t", description: "\tWith steamed mixed vegetables and white riceWith steamed mixed vegetables and white rice\t", category: "\tChicken\t", restaurant_id: 3, archived: false, price: 7.0},
  {name: "\tEgg Rolls\t", description: "\tMany flavors\t", category: "\tSides\t", restaurant_id: 3, archived: false, price: 4.0},
  {name: "\tSpring Rolls\t", description: "\tMany flavors\t", category: "\tSides\t", restaurant_id: 3, archived: false, price: 3.0},
  {name: "\tCrab Rangoon\t", description: "\tCrab flavored\t", category: "\tSides\t", restaurant_id: 3, archived: false, price: 3.5},
  {name: "\tSoup\t", description: "\tEgg drop or miso\t", category: "\tSides\t", restaurant_id: 3, archived: false, price: 2.3},
  {name: "\tKung Pao Chicken\t", description: "\tVery spice!\t", category: "\tChicken\t", restaurant_id: 3, archived: false, price: 8.0},
  {name: "\tTeriyaki Chicken\t", description: "\tWith steamed mixed vegetables and white rice\t", category: "\tChicken\t", restaurant_id: 3, archived: false, price: 9.0},
  {name: "\tOrange Chicken\t", description: "\tFried with orange sauce\t", category: "\tChicken\t", restaurant_id: 3, archived: false, price: 11.0},
  {name: "\tMu Shu Pork\t", description: "\tMmmmmm\t", category: "\tPork\t", restaurant_id: 3, archived: false, price: 11.0},
  {name: "\tSzechuan Pork\t", description: "\tMmmmmm\t", category: "\tPork\t", restaurant_id: 3, archived: false, price: 12.0},
  {name: "\tBBQ Beef\t", description: "\tMmmmmm\t", category: "\tBeef\t", restaurant_id: 3, archived: false, price: 9.0},
  {name: "\tBeef Teriyaki\t", description: "\tMmmmmm\t", category: "\tBeef\t", restaurant_id: 3, archived: false, price: 8.0},
  {name: "\tKung Pao Beef\t", description: "\tMmmmmm\t", category: "\tBeef\t", restaurant_id: 3, archived: false, price: 8.0},
  {name: "\tPeppered Beef\t", description: "\tMmmmmm\t", category: "\tBeef\t", restaurant_id: 3, archived: false, price: 9.0},
  {name: "\tBiryani\t", description: "\tAuthentic Pakistani\t", category: "\tPakistani\t", restaurant_id: 4, archived: false, price: 6.0},
  {name: "\tCreamy Moong Daal\t", description: "\tAuthentic Pakistani\t", category: "\tPakistani\t", restaurant_id: 4, archived: false, price: 4.0},
  {name: "\tKashmiri Chai\t", description: "\tAuthentic Pakistani\t", category: "\tPakistani\t", restaurant_id: 4, archived: false, price: 5.0},
  {name: "\tNihari\t", description: "\tAuthentic Pakistani\t", category: "\tPakistani\t", restaurant_id: 4, archived: false, price: 6.0},
  {name: "\tFalooda\t", description: "\tAuthentic Pakistani\t", category: "\tPakistani\t", restaurant_id: 4, archived: false, price: 3.0},
  {name: "\tKeema\t", description: "\tAuthentic Pakistani\t", category: "\tPakistani\t", restaurant_id: 4, archived: false, price: 12.0},
  {name: "\tHaleem\t", description: "\tAuthentic Pakistani\t", category: "\tPakistani\t", restaurant_id: 4, archived: false, price: 9.0},
  {name: "\tNaan\t", description: "\tAuthentic Pakistani\t", category: "\tPakistani\t", restaurant_id: 4, archived: false, price: 12.0},
  {name: "\tChicken Jalfrezi\t", description: "\tAuthentic Pakistani\t", category: "\tPakistani\t", restaurant_id: 4, archived: false, price: 13.0},
  {name: "\tAloo Gohst\t", description: "\tAuthentic Pakistani\t", category: "\tPakistani\t", restaurant_id: 4, archived: false, price: 10.0},
  {name: "\tChicken Curry\t", description: "\tAuthentic Pakistani\t", category: "\tPakistani\t", restaurant_id: 4, archived: false, price: 9.5},
  {name: "\tChicken Karahi\t", description: "\tAuthentic Pakistani\t", category: "\tPakistani\t", restaurant_id: 4, archived: false, price: 8.5},
  {name: "\tTurkey Chili\t", description: "\tOrder quickly, quietly.\t", category: "\tSoups\t", restaurant_id: 3, archived: false, price: 5.0},
  {name: "\tCrab Bisque\t", description: "\tOrder quickly, quietly.\t", category: "\tSoups\t", restaurant_id: 3, archived: false, price: 4.0},
  {name: "\tMulligatawny\t", description: "\tOrder quickly, quietly.\t", category: "\tSoups\t", restaurant_id: 3, archived: false, price: 5.0},
  {name: "\tJumbalya\t", description: "\tOrder quickly, quietly.\t", category: "\tSoups\t", restaurant_id: 3, archived: false, price: 4.0},
  {name: "\tChicken Noodle\t", description: "\tOrder quickly, quietly.\t", category: "\tSoups\t", restaurant_id: 3, archived: false, price: 5.0},
  {name: "\tTomato\t", description: "\tOrder quickly, quietly.\t", category: "\tSoups\t", restaurant_id: 3, archived: false, price: 4.0},
  {name: "\tWild Mushroom\t", description: "\tOrder quickly, quietly.\t", category: "\tSoups\t", restaurant_id: 3, archived: false, price: 5.0},
  {name: "\tCold Cucumber\t", description: "\tOrder quickly, quietly.\t", category: "\tSoups\t", restaurant_id: 3, archived: false, price: 4.0},
  {name: "\tCorn and Crab Chowder\t", description: "\tOrder quickly, quietly.\t", category: "\tSoups\t", restaurant_id: 3, archived: false, price: 5.0},
  {name: "\tSpaghetti and Meatballs\t", description: "\tPerfecto!\t", category: "\tPastas\t", restaurant_id: 5, archived: false, price: 12.0},
  {name: "\tRissoto\t", description: "\tPerfecto!\t", category: "\tPastas\t", restaurant_id: 5, archived: false, price: 11.0},
  {name: "\tPenne with Chicken\t", description: "\tPerfecto!\t", category: "\tPastas\t", restaurant_id: 5, archived: false, price: 18.0},
  {name: "\tPasta Primavera\t", description: "\tPerfecto!\t", category: "\tPastas\t", restaurant_id: 5, archived: false, price: 21.0},
  {name: "\tPan Crusted Tilapia\t", description: "\tPerfecto!\t", category: "\tFish\t", restaurant_id: 5, archived: false, price: 23.0},
  {name: "\tSeared Tuna\t", description: "\tPerfecto!\t", category: "\tFish\t", restaurant_id: 5, archived: false, price: 19.0},
  {name: "\tFried Sole\t", description: "\tPerfecto!\t", category: "\tFish\t", restaurant_id: 5, archived: false, price: 18.0},
  {name: "\tThe Duck\t", description: "\tSo succulent...so succulent!\t", category: "\tPoultry\t", restaurant_id: 5, archived: false, price: 24.0},
  {name: "\tBreadsticks\t", description: "\tPerfecto!\t", category: "\tBread\t", restaurant_id: 5, archived: false, price: 17.0},
  {name: "\tBreadsticks with Cheese\t", description: "\tPerfecto!\t", category: "\tBread\t", restaurant_id: 5, archived: false, price: 18.0},
  {name: "\tSliced Bread\t", description: "\tPerfecto!\t", category: "\tBread\t", restaurant_id: 5, archived: false, price: 24.0},
  {name: "\tCabernet\t", description: "\tPerfecto!\t", category: "\tDrinks\t", restaurant_id: 5, archived: false, price: 8.0},
  {name: "\tMerlot\t", description: "\tPerfecto!\t", category: "\tDrinks\t", restaurant_id: 5, archived: false, price: 9.0},
  {name: "\tChardonnay\t", description: "\tPerfecto!\t", category: "\tDrinks\t", restaurant_id: 5, archived: false, price: 7.0},
  {name: "\tChampagne\t", description: "\tPerfecto!\t", category: "\tDrinks\t", restaurant_id: 5, archived: false, price: 8.0},
  {name: "\tSpaghetti and Meatballs\t", description: "\tPerfecto!\t", category: "\tPastas\t", restaurant_id: 6, archived: false, price: 12.0},
  {name: "\tRissoto\t", description: "\tPerfecto!\t", category: "\tPastas\t", restaurant_id: 6, archived: false, price: 11.0},
  {name: "\tPenne with Chicken\t", description: "\tPerfecto!\t", category: "\tPastas\t", restaurant_id: 6, archived: false, price: 18.0},
  {name: "\tPasta Primavera\t", description: "\tPerfecto!\t", category: "\tPastas\t", restaurant_id: 6, archived: false, price: 21.0},
  {name: "\tPan Crusted Tilapia\t", description: "\tPerfecto!\t", category: "\tFish\t", restaurant_id: 6, archived: false, price: 23.0},
  {name: "\tSeared Tuna\t", description: "\tPerfecto!\t", category: "\tFish\t", restaurant_id: 6, archived: false, price: 19.0},
  {name: "\tFried Sole\t", description: "\tPerfecto!\t", category: "\tFish\t", restaurant_id: 6, archived: false, price: 18.0},
  {name: "\tBreadsticks\t", description: "\tPerfecto!\t", category: "\tBread\t", restaurant_id: 6, archived: false, price: 17.0},
  {name: "\tBreadsticks with Cheese\t", description: "\tPerfecto!\t", category: "\tBread\t", restaurant_id: 6, archived: false, price: 18.0},
  {name: "\tSliced Bread\t", description: "\tPerfecto!\t", category: "\tBread\t", restaurant_id: 6, archived: false, price: 24.0},
  {name: "\tCabernet\t", description: "\tPerfecto!\t", category: "\tDrinks\t", restaurant_id: 6, archived: false, price: 8.0},
  {name: "\tMerlot\t", description: "\tPerfecto!\t", category: "\tDrinks\t", restaurant_id: 6, archived: false, price: 9.0},
  {name: "\tChardonnay\t", description: "\tPerfecto!\t", category: "\tDrinks\t", restaurant_id: 6, archived: false, price: 7.0},
  {name: "\tChampagne\t", description: "\tPerfecto!\t", category: "\tDrinks\t", restaurant_id: 6, archived: false, price: 8.0},
  {name: "\tMarbel Rye\t", description: "\tPerfect for a dinner party \t", category: "\tBreads\t", restaurant_id: 7, archived: false, price: 8.0},
  {name: "\tCinnamon Swirl\t", description: "\tDecent for a dinner party\t", category: "\tBreads\t", restaurant_id: 7, archived: false, price: 9.0},
  {name: "\tLemon\t", description: "\tVery lemony\t", category: "\tBreads\t", restaurant_id: 7, archived: false, price: 7.0},
  {name: "\tPumpkin\t", description: "\tThe most autumnal\t", category: "\tBreads\t", restaurant_id: 7, archived: false, price: 8.0},
  {name: "\tBlack and White Cookie\t", description: "\tTwo races of flavor living side by side. It's a wonderful thing isn't it?\t", category: "\tCookies\t", restaurant_id: 7, archived: false, price: 3.0},
  {name: "\tChocolate Chip\t", description: "\tClassic\t", category: "\tCookies\t", restaurant_id: 7, archived: false, price: 2.0},
  {name: "\tMolasses\t", description: "\tDelicious\t", category: "\tCookies\t", restaurant_id: 7, archived: false, price: 2.0},
  {name: "\tPumpkin\t", description: "\tBest with whipped Cream\t", category: "\tPies\t", restaurant_id: 7, archived: false, price: 9.0},
  {name: "\tApple\t", description: "\tLike apple pie\t", category: "\tPies\t", restaurant_id: 7, archived: false, price: 9.0},
  {name: "\tLemon Meringue\t", description: "\tNice and tart\t", category: "\tPies\t", restaurant_id: 7, archived: false, price: 9.0},
  {name: "\tGeneral Tso Chicken\t", description: "\tWith steamed mixed vegetables and white riceWith steamed mixed vegetables and white rice\t", category: "\tChicken\t", restaurant_id: 8, archived: false, price: 7.0},
  {name: "\tEgg Rolls\t", description: "\tMany flavors\t", category: "\tSides\t", restaurant_id: 8, archived: false, price: 4.0},
  {name: "\tSpring Rolls\t", description: "\tMany flavors\t", category: "\tSides\t", restaurant_id: 8, archived: false, price: 3.0},
  {name: "\tCrab Rangoon\t", description: "\tCrab flavored\t", category: "\tSides\t", restaurant_id: 8, archived: false, price: 3.5},
  {name: "\tSoup\t", description: "\tEgg drop or miso\t", category: "\tSides\t", restaurant_id: 8, archived: false, price: 2.3},
  {name: "\tKung Pao Chicken\t", description: "\tVery spice!\t", category: "\tChicken\t", restaurant_id: 8, archived: false, price: 8.0},
  {name: "\tTeriyaki Chicken\t", description: "\tWith steamed mixed vegetables and white rice\t", category: "\tChicken\t", restaurant_id: 8, archived: false, price: 9.0},
  {name: "\tOrange Chicken\t", description: "\tFried with orange sauce\t", category: "\tChicken\t", restaurant_id: 8, archived: false, price: 11.0},
  {name: "\tMu Shu Pork\t", description: "\tMmmmmm\t", category: "\tPork\t", restaurant_id: 8, archived: false, price: 11.0},
  {name: "\tSzechuan Pork\t", description: "\tMmmmmm\t", category: "\tPork\t", restaurant_id: 8, archived: false, price: 12.0},
  {name: "\tBBQ Beef\t", description: "\tMmmmmm\t", category: "\tBeef\t", restaurant_id: 8, archived: false, price: 9.0},
  {name: "\tBeef Teriyaki\t", description: "\tMmmmmm\t", category: "\tBeef\t", restaurant_id: 8, archived: false, price: 8.0},
  {name: "\tKung Pao Beef\t", description: "\tMmmmmm\t", category: "\tBeef\t", restaurant_id: 8, archived: false, price: 8.0},
  {name: "\tPeppered Beef\t", description: "\tMmmmmm\t", category: "\tBeef\t", restaurant_id: 8, archived: false, price: 9.0},
  {name: "\tThe Original Frankfurter\t", description: "\tReally\t", category: "\tFranks and Sausages\t", restaurant_id: 9, archived: false, price: 5.0},
  {name: "\tHome Run\t", description: "\tFrank topped with sauerkraut, NY Onions, and mustard\t", category: "\tFranks and Sausages\t", restaurant_id: 9, archived: false, price: 4.0},
  {name: "\tSlaw Dog\t", description: "\tFrank topped with coleslaw and sweet pickles\t", category: "\tFranks and Sausages\t", restaurant_id: 9, archived: false, price: 4.5},
  {name: "\t100% All-Beef SPICY Smoked Sausage\t", description: "\tWith grilled peppers and onions\t", category: "\tFranks and Sausages\t", restaurant_id: 9, archived: false, price: 5.0},
  {name: "\tPapaya\t", description: "\tAll natural, blended in house daily\t", category: "\tTropical Drinks\t", restaurant_id: 9, archived: false, price: 6.0},
  {name: "\tMango\t", description: "\tAll natural, blended in house daily\t", category: "\tTropical Drinks\t", restaurant_id: 9, archived: false, price: 6.0},
  {name: "\tCoconut Champagne\t", description: "\tAll natural, blended in house daily\t", category: "\tTropical Drinks\t", restaurant_id: 9, archived: false, price: 6.0},
  {name: "\tPina Colada\t", description: "\tAll natural, blended in house daily\t", category: "\tTropical Drinks\t", restaurant_id: 9, archived: false, price: 6.0},
  {name: "\tBanana Daquiri\t", description: "\tAll natural, blended in house daily\t", category: "\tTropical Drinks\t", restaurant_id: 9, archived: false, price: 6.0},
  {name: "\tStrawberry Supreme\t", description: "\tAll natural, blended in house daily\t", category: "\tTropical Drinks\t", restaurant_id: 9, archived: false, price: 6.0},
  {name: "\tTuna Salad\t", description: "\tWith lettuce and tomato on a croissant\t", category: "\tSandwiches\t", restaurant_id: 10, archived: false, price: 12.0},
  {name: "\tBLT\t", description: "\tBacon, lettuc and tomato\t", category: "\tSandwiches\t", restaurant_id: 10, archived: false, price: 11.0},
  {name: "\tHot Pastrami\t", description: "\tVoted #1\t", category: "\tSandwiches\t", restaurant_id: 10, archived: false, price: 10.0},
  {name: "\tItalian\t", description: "\tPastrami, ham, and capicola\t", category: "\tSandwiches\t", restaurant_id: 10, archived: false, price: 11.0},
  {name: "\tVeggie\t", description: "\tFor the vegetarians\t", category: "\tSandwiches\t", restaurant_id: 10, archived: false, price: 10.0},
  {name: "\tGrilled Chicken\t", description: "\tGrilled chicken breast, lettuce and tomato\t", category: "\tSandwiches\t", restaurant_id: 10, archived: false, price: 11.0},
  {name: "\tCorned Beef\t", description: "\tA classic \t", category: "\tSandwiches\t", restaurant_id: 10, archived: false, price: 10.0},
  {name: "\tSalami\t", description: "\tAnother classic\t", category: "\tSandwiches\t", restaurant_id: 10, archived: false, price: 9.0},
  {name: "\tChicken Noodle\t", description: "\tGreat paired with any sandwich\t", category: "\tSoups\t", restaurant_id: 10, archived: false, price: 4.0},
  {name: "\tLobster Bisque\t", description: "\tTry it with the BLT\t", category: "\tSoups\t", restaurant_id: 10, archived: false, price: 5.0},
  {name: "\tMushroom\t", description: "\tThe heartiest\t", category: "\tSoups\t", restaurant_id: 10, archived: false, price: 4.5},
  {name: "\tTomato\t", description: "\tGreat with the veggie sandwich\t", category: "\tSoups\t", restaurant_id: 10, archived: false, price: 5.0},
  {name: "\tFried Chicken Bucket\t", description: "\tWith cole slaw and mashed potatoes\t", category: "\tDinners\t", restaurant_id: 11, archived: false, price: 12.0},
  {name: "\tGrilled Chicken Bucket\t", description: "\tWith cole slaw and mashed potatoes\t", category: "\tDinners\t", restaurant_id: 11, archived: false, price: 15.0},
  {name: "\tWhole Chicken\t", description: "\tA pretty mean bird\t", category: "\tDinners\t", restaurant_id: 11, archived: false, price: 13.0},
  {name: "\tHalf Chicken\t", description: "\tHalf of a pretty mean bird\t", category: "\tDinners\t", restaurant_id: 11, archived: false, price: 12.0},
  {name: "\tBBQ Chicken\t", description: "\t4-5 pieces, southern style\t", category: "\tDinners\t", restaurant_id: 11, archived: false, price: 10.0},
  {name: "\tMacaroni and Cheese\t", description: "\tMade in house\t", category: "\tSides\t", restaurant_id: 11, archived: false, price: 5.0},
  {name: "\tPork and Beans\t", description: "\tMade in house\t", category: "\tSides\t", restaurant_id: 11, archived: false, price: 6.0},
  {name: "\tMashed Potatoes\t", description: "\tMade in house\t", category: "\tSides\t", restaurant_id: 11, archived: false, price: 5.0},
  {name: "\tBroccoli\t", description: "\tKramer's favorite\t", category: "\tSides\t", restaurant_id: 11, archived: false, price: 4.0},
  {name: "\tCole Slaw\t", description: "\tMade in house\t", category: "\tSides\t", restaurant_id: 11, archived: false, price: 6.0},
  {name: "\tNormal-sized salad\t", description: "\tJust a normal salad\t", category: "\tSalads\t", restaurant_id: 12, archived: false, price: 5.0},
  {name: "\tChef Salad\t", description: "\tWith a hard-boild egg, ranch dressing\t", category: "\tSalads\t", restaurant_id: 12, archived: false, price: 5.5},
  {name: "\tGreek Salad\t", description: "\tWith check, feta cheese, and olives\t", category: "\tSalads\t", restaurant_id: 12, archived: false, price: 6.5},
  {name: "\tChicken Sandwich\t", description: "\tOn a burger bun with lettuce and tomato\t", category: "\tSandwiches\t", restaurant_id: 12, archived: false, price: 6.0},
  {name: "\tThe Reuben\t", description: "\tOn rye bread, with sauerkraut\t", category: "\tSandwiches\t", restaurant_id: 12, archived: false, price: 7.5},
  {name: "\tBLT\t", description: "\tBacon, lettuce, and tomato with fries\t", category: "\tSandwiches\t", restaurant_id: 12, archived: false, price: 5.5},
  {name: "\tHambuger\t", description: "\tQuarter or triple pounder with American cheese with fries\t", category: "\tSandwiches\t", restaurant_id: 12, archived: false, price: 6.5},
  {name: "\tBacon and Eggs\t", description: "\t2 eggs (any style) with two slices of bacon, and bread\t", category: "\tBreakfast\t", restaurant_id: 12, archived: false, price: 8.0},
  {name: "\tOmelette\t", description: "\t3 eggs, with any combination of toppings\t", category: "\tBreakfast\t", restaurant_id: 12, archived: false, price: 7.0},
  {name: "\tPancakes\t", description: "\t3 pancakes, with butter and maple syrup\t", category: "\tBreakfast\t", restaurant_id: 12, archived: false, price: 7.0},
  {name: "\tFlapjacks\t", description: "\tLike pancakes, but smaller\t", category: "\tBreakfast\t", restaurant_id: 12, archived: false, price: 6.0},
  {name: "\tSoda\t", description: "\tCoke products\t", category: "\tBeverages\t", restaurant_id: 12, archived: false, price: 2.0},
  {name: "\tJuice\t", description: "\tOrange or apple\t", category: "\tBeverages\t", restaurant_id: 12, archived: false, price: 2.0},
  {name: "\tMilk\t", description: "\tWhite or chocolate\t", category: "\tBeverages\t", restaurant_id: 12, archived: false, price: 3.0},
  {name: "\tMilkshake\t", description: "\tChocolate, vanilla, or mixed\t", category: "\tBeverages\t", restaurant_id: 12, archived: false, price: 4.0},
  {name: "\tChicken Fingers\t", description: "\tWith Fries and a pickle\t", category: "\tLunch\t", restaurant_id: 13, archived: false, price: 8.0},
  {name: "\tHamburger\t", description: "\tQuarter pounder with fries and a pickle\t", category: "\tLunch\t", restaurant_id: 13, archived: false, price: 9.0},
  {name: "\tChicken Sandwich\t", description: "\tWith lettuce and tomato\t", category: "\tLunch\t", restaurant_id: 13, archived: false, price: 8.0},
  {name: "\tTacos\t", description: "\t3, chicken or beef\t", category: "\tLunch\t", restaurant_id: 13, archived: false, price: 9.0},
  {name: "\tChicken Fingers\t", description: "\tWith Fries and a pickle\t", category: "\tLate Night\t", restaurant_id: 13, archived: false, price: 6.0},
  {name: "\tHamburger\t", description: "\tQuarter pounder with fries and a pickle\t", category: "\tLate Night\t", restaurant_id: 13, archived: false, price: 7.0},
  {name: "\tChicken Sandwich\t", description: "\tWith lettuce and tomato\t", category: "\tLate Night\t", restaurant_id: 13, archived: false, price: 6.0},
  {name: "\tTacos\t", description: "\t3, chicken or beef\t", category: "\tLate Night\t", restaurant_id: 13, archived: false, price: 7.0},
  {name: "\tPoppyseed Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tClassics\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tGarlic Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tClassics\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tRye Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tClassics\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tPumpernickel Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tClassics\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tEverything Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tClassics\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tSesame Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tClassics\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tOnion Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tClassics\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tEgg Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tClassics\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tSalt Poppy Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tClassics\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tPan Baked Water Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tClassics\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tHearth Baked Water Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tClassics\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tBanana Nut Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tSweet\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tStrawberry Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tSweet\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tChocolate Chip Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tSweet\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tCranberry Apple Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tSweet\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tBlueberry Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tSweet\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tCinnamon Raisin Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tSweet\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tPizza Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tNew Styles\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tJalapeno Cheese Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tNew Styles\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tOnion Cheese Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tNew Styles\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tCheese Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tNew Styles\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tOat Bran Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tHealthy\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tWhole Wheat Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tHealthy\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\t9 Grain Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tHealthy\t", restaurant_id: 14, archived: false, price: 4.0},
  {name: "\tSourdough Bagel\t", description: "\tNo bagels, no bagels, no bagels\t", category: "\tHealthy\t", restaurant_id: 14, archived: false, price: 4.0}
])
Restaurant.create!([
  {name: "Monk's Cafe", cuisine: "American", address: "2880 Broadway", city: "New York City", state: "NY", yelp_id: nil, opens_at: 800, closes_at: 2200, delivery_min: 12.0, delivery_fee: 2.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/1.jpg"},
  {name: "Hop Shing", cuisine: "Chinese", address: "9 Chatham Square", city: "New York City", state: "NY", yelp_id: nil, opens_at: 800, closes_at: 2200, delivery_min: 8.0, delivery_fee: 1.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/2.jpg"},
  {name: "Soup Stand", cuisine: "Soups", address: "259-A West 55th Street", city: "New York City", state: "NY", yelp_id: nil, opens_at: 1100, closes_at: 1800, delivery_min: 0.0, delivery_fee: 0.0, takeout_only: true, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/3.jpg"},
  {name: "Dream Cafe", cuisine: "Pakistani", address: "478 9th Ave", city: "New York City", state: "NY", yelp_id: nil, opens_at: 1000, closes_at: 2200, delivery_min: 4.75, delivery_fee: 3.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/4.jpg"},
  {name: "Pomodoro Roso", cuisine: "Italian", address: "229 Columbus Ave", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1300, closes_at: 2300, delivery_min: 0.0, delivery_fee: 0.0, takeout_only: true, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/5.jpg"},
  {name: "Paisano", cuisine: "Italian", address: "2287 1st Ave\t1100", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1100, closes_at: 2200, delivery_min: 0.0, delivery_fee: 0.0, takeout_only: true, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/6.jpg"},
  {name: "Royale Pastry Shop", cuisine: "Bakery", address: "237 West 72nd St", city: "New York City", state: "New York", yelp_id: nil, opens_at: 800, closes_at: 2200, delivery_min: 12.0, delivery_fee: 3.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/7.jpg"},
  {name: "Hunan 5th Avenue", cuisine: "Chinese", address: "323 5th Ave", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1100, closes_at: 2200, delivery_min: 0.0, delivery_fee: 0.0, takeout_only: true, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/8.jpg"},
  {name: "Papaya King", cuisine: "Hot Dogs", address: "2090 Broadway", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1130, closes_at: 2100, delivery_min: 10.0, delivery_fee: 3.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/9.jpg"},
  {name: "Mendy's", cuisine: "Deli", address: "61 E. 64th Street", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1030, closes_at: 2200, delivery_min: 12.0, delivery_fee: 2.5, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/10.jpg"},
  {name: "Kenny Roger's Roasters", cuisine: "American", address: "2055 Broadway", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1000, closes_at: 2200, delivery_min: 15.0, delivery_fee: 2.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/11.jpg"},
  {name: "Beach Café", cuisine: "American", address: "1326 Second Ave", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1200, closes_at: 2300, delivery_min: 12.0, delivery_fee: 2.5, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/12.jpg"},
  {name: "Pete's Tavern", cuisine: "American", address: "129 E. 18th St", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1100, closes_at: 2300, delivery_min: 0.0, delivery_fee: 0.0, takeout_only: true, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/13.jpg"},
  {name: "H & H Bagles", cuisine: "Bakery", address: "2239 Broadway", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1100, closes_at: 2300, delivery_min: 8.0, delivery_fee: 1.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/14.jpg"},
  {name: "Reggie's Diner", cuisine: "American", address: "682 11th Ave", city: "New York City", state: "New York", yelp_id: nil, opens_at: 800, closes_at: 2300, delivery_min: 12.0, delivery_fee: 4.0, takeout_only: false, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/15.jpg"},
  {name: "Fitzpatrick's Bar and Grill", cuisine: "American", address: "1641 Second Ave", city: "New York City", state: "New York", yelp_id: nil, opens_at: 1200, closes_at: 2300, delivery_min: 0.0, delivery_fee: 0.0, takeout_only: true, image_link: "https://dl.dropboxusercontent.com/u/4448887/seinfood/16.jpg"}
])
User.create!([
  {email: "test@email.com", password_digest: "$2a$10$J64WLijHUUXbjU7p5AB7wuX0UF55aNdgoSLt3eON.xemeGovOH98i", session_token: "Zkxai_v1-MiEDx3ouwfplQ", address: "129 West 81st St", city: "New York City", state: "New York", name: "Default User"}
])
